# Generated by Django 5.2.8 on 2025-11-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, default='https://azharfa.my.id', null=True),
        ),
    ]
