# Generated by Django 5.2.8 on 2025-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, default='Fullstack Developer', max_length=50, null=True),
        ),
    ]
